### ISSUE TITLE
Getting An Error on every request

### ISSUE THREAD

**Issue by maxjamesdemo** [ContextLogic/Wish-Merchant-API#7]
On every request I'm getting a
`Accessing static property Wish\WishSession::$merchant_id as non static`
Exception

Here's my code, super simple:

```
    $this->client = new WishClient($this->token->access_token, 'prod');
    $orders = $this->client->getAllUnfulfilledOrdersSince(date('Y-m-d', strtotime('now - 30 days')));
```

**Comment by zerongjiang** [comment]
Should be fixed in https://github.com/ContextLogic/Wish-Merchant-API/commit/f00de2bb3cd43326897f94029fb024d77dbade57
